[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && node server.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
